"""Deterministic brand exports. Requires Python 3 and ImageMagick (magick)."""
import json, pathlib, re, subprocess
ROOT = pathlib.Path(__file__).resolve().parents[2]
spec = json.loads((pathlib.Path(__file__).parent / 'mark_geometry.json').read_text())
BG, FG = spec['background'], spec['foreground']
OUT = ROOT / 'assets/branding'
OUT.mkdir(parents=True, exist_ok=True)

def svg(size=100, background=False, scale=1, offset=0):
    back = f'<rect width="{size}" height="{size}" fill="{BG}"/>' if background else ''
    paths = ''.join(f'<path id="{p["id"]}" d="{p["d"]}"/>' for p in spec['paths'])
    return f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" viewBox="0 0 {size} {size}">{back}<g fill="{FG}" transform="translate({offset} {offset}) scale({scale})">{paths}</g></svg>\n'

def raster(source, destination, size, opaque=False):
    destination.parent.mkdir(parents=True, exist_ok=True)
    command = ['magick', '-background', 'none', '-density', '1536', str(source), '-resize', f'{size}x{size}']
    if opaque: command += ['-background', BG, '-alpha', 'remove', '-alpha', 'off']
    subprocess.run(command + ['-depth', '8', '-strip', str(destination)], check=True)

(OUT / 'nova-mark.svg').write_text(svg())
(OUT / 'nova-app-icon.svg').write_text(svg(background=True, scale=.64, offset=18))
raster(OUT / 'nova-app-icon.svg', OUT / 'nova-app-icon.png', 1024, True)
raster(OUT / 'nova-mark.svg', OUT / 'nova-mark.png', 512)
# The launcher supplies its own mask; no rounded container is baked into the icon.
RES = ROOT / 'android/app/src/main/res'
for density, size in [('mdpi',48),('hdpi',72),('xhdpi',96),('xxhdpi',144),('xxxhdpi',192)]:
    raster(OUT / 'nova-app-icon.svg', RES / f'mipmap-{density}/ic_launcher.png', size, True)

def vector(size, scale, offset, color=FG):
    paths = ''.join(f'        <path android:fillColor="{color}" android:pathData="{p["d"]}" />\n' for p in spec['paths'])
    return f'''<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="{size}dp" android:height="{size}dp" android:viewportWidth="{size}" android:viewportHeight="{size}">
    <group android:scaleX="{scale}" android:scaleY="{scale}" android:translateX="{offset}" android:translateY="{offset}">
{paths}    </group>
</vector>
'''
(RES/'drawable/nova_icon_foreground.xml').write_text(vector(108,.52,28))
(RES/'drawable/nova_splash_icon.xml').write_text(vector(288,1.12,88))
(RES/'drawable/nova_launch_mark.xml').write_text(vector(112,1.12,0))
for version in ['v26','v33']:
    folder=RES/f'mipmap-anydpi-{version}'; folder.mkdir(exist_ok=True)
    mono='\n    <monochrome android:drawable="@drawable/nova_icon_foreground" />' if version=='v33' else ''
    (folder/'ic_launcher.xml').write_text(f'''<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/nova_black" />
    <foreground android:drawable="@drawable/nova_icon_foreground" />{mono}
</adaptive-icon>
''')
# Existing iOS catalog metadata remains the source of the required sizes.
catalog = ROOT/'ios/Runner/Assets.xcassets/AppIcon.appiconset'
for item in json.loads((catalog/'Contents.json').read_text())['images']:
    size=round(float(item['size'].split('x')[0])*float(item['scale'].removesuffix('x')))
    raster(OUT/'nova-app-icon.svg', catalog/item['filename'], size, True)
launch=ROOT/'ios/Runner/Assets.xcassets/LaunchImage.imageset'
for suffix, scale in [('',1),('@2x',2),('@3x',3)]:
    raster(OUT/'nova-mark.svg',launch/f'LaunchImage{suffix}.png',112*scale)
# Share the exact source geometry with Flutter without a runtime SVG dependency.
methods=[]
for p in spec['paths']:
    tokens=re.findall(r'[MLQCZ]|-?\d+(?:\.\d+)?',p['d'])
    i=0; instructions=[]
    verbs={'M':('moveTo',2),'L':('lineTo',2),'Q':('quadraticBezierTo',4),'C':('cubicTo',6),'Z':('close',0)}
    while i<len(tokens):
        verb,count=verbs[tokens[i]]; args=', '.join(tokens[i+1:i+1+count]); i+=count+1
        instructions.append(f'    ..{verb}({args})')
    methods.append('  static Path '+p['id']+'() => Path()\n'+'\n'.join(instructions)+';')
dart=ROOT/'lib/core/branding/nova_geometry.dart'; dart.parent.mkdir(parents=True,exist_ok=True)
dart.write_text('// Generated by tools/branding/export_brand.py from mark_geometry.json.\nimport \'dart:ui\';\n\nabstract final class NovaGeometry {\n'+'\n\n'.join(methods)+'\n}\n')
(OUT/'manifest.json').write_text(json.dumps({'name':spec['name'],'palette':{'background':BG,'foreground':FG},'source':'tools/branding/mark_geometry.json','concept':'Built-in ImageGen; rebuilt as clean, deterministic vector geometry for native and Flutter rendering.','exports':['nova-mark.svg','nova-mark.png','nova-app-icon.svg','nova-app-icon.png'],'adaptive_safe_zone':'Foreground contained inside the central 66dp circle of the 108dp viewport.'},indent=2)+'\n')
print('Exported SVG/PNG masters, Android legacy/adaptive/themed icons, iOS icons/launch images, and shared Flutter geometry.')
