// Generated by tools/branding/export_brand.py from mark_geometry.json.
import 'dart:ui';

abstract final class NovaGeometry {
  static Path leftFold() => Path()
    ..moveTo(8, 27)
    ..lineTo(31, 50)
    ..quadraticBezierTo(34, 53, 34, 57)
    ..lineTo(34, 85)
    ..quadraticBezierTo(34, 89, 31, 91)
    ..lineTo(26, 94)
    ..quadraticBezierTo(24, 95, 21, 95)
    ..lineTo(12, 95)
    ..quadraticBezierTo(8, 95, 8, 91)
    ..close();

  static Path rightFold() => Path()
    ..moveTo(79, 5)
    ..lineTo(88, 5)
    ..quadraticBezierTo(92, 5, 92, 9)
    ..lineTo(92, 69)
    ..lineTo(71, 43)
    ..quadraticBezierTo(68, 39, 68, 35)
    ..lineTo(68, 19)
    ..quadraticBezierTo(68, 16, 71, 13)
    ..lineTo(76, 7)
    ..quadraticBezierTo(77, 5, 79, 5)
    ..close();

  static Path diagonal() => Path()
    ..moveTo(14, 5)
    ..lineTo(29, 5)
    ..quadraticBezierTo(32, 5, 34, 8)
    ..lineTo(90, 77)
    ..quadraticBezierTo(92, 79, 92, 82)
    ..lineTo(92, 90)
    ..quadraticBezierTo(92, 95, 87, 95)
    ..lineTo(72, 95)
    ..quadraticBezierTo(69, 95, 67, 92)
    ..lineTo(10, 22)
    ..quadraticBezierTo(6, 17, 9, 11)
    ..quadraticBezierTo(10, 5, 14, 5)
    ..close();
}
